name: pokemon_trivia
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.0
  flutter_bloc: ^7.0.0
  get_it: ^7.2.0
  sqflite: ^2.0.0
  path: ^1.8.0
  logger: ^1.0.0
  shared_preferences: ^2.0.6
  device_info: ^2.0.2
  google_fonts: ^4.0.4
  path_provider: ^2.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/
